title: Greeble Gardens
description: Welcome to my version of a Python discord bot with a Lite side use of MySql. Yet another chance for me to create a solution to a problem.
google_analytics:
remote_theme: pages-themes/dinky@v0.2.0
